[package]
name                    =  "xdpy"
version                 =  "0.0.1"
description             =  "raw XDP socket library for high-load networking"
authors                 = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license                 =  "MIT"
repository              =  "https://github.com/ponyatov/xdpy"
edition                 =  "2024"

[[bin]]
name                    = "recv"
path                    = "src/recv.rs"

[[bin]]
name                    = "send"
path                    = "src/send.rs"

[lib]
name                    = "bpf"
path                    = "src/bpf.rs"
crate-type              = ["cdylib"]

[dependencies]
const_format            = "0.2"
nom                     = { version = "8.0", default-features = false}#, features = ["alloc"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc                    = "0.2"
memmap2                 = "0.9"

[target.x86_64-unknown-linux-gnu.dependencies]
#xdpilone                = "1.2"

[target.bpfel-unknown-none.dependencies]
aya = { version = "0.13", default-features = false}#features = ["async"] }

[features]
# hw
pc                      = ["i5"]
# cpu
i5                      = ["x86_64"]
# arch
x86_64                  = ["linux"]
# os
linux                   = []
# network
bpf                     = []
